import type { FlociCloudDefaults, FlociCloudProvider } from '../types/index.js';

export const flociCloudDefaults = {
  aws: {
    cloud: 'aws',
    image: 'floci/floci:latest',
    port: 4566,
    endpoint: 'http://localhost:4566',
    containerName: 'fdekit-floci-aws',
    endpointEnvName: 'AWS_ENDPOINT_URL',
    portEnvName: 'FLOCI_PORT',
    baseUrlEnvName: 'FLOCI_BASE_URL',
    hostnameEnvName: 'FLOCI_HOSTNAME',
    storageModeEnvName: 'FLOCI_STORAGE_MODE',
    storagePathEnvName: 'FLOCI_STORAGE_PERSISTENT_PATH',
    dockerNetworkEnvName: 'FLOCI_SERVICES_DOCKER_NETWORK',
  },
  azure: {
    cloud: 'azure',
    image: 'floci/floci-az:latest',
    port: 4577,
    endpoint: 'http://localhost:4577',
    containerName: 'fdekit-floci-azure',
    endpointEnvName: 'AZURE_ENDPOINT_URL',
    portEnvName: 'FLOCI_AZ_PORT',
    baseUrlEnvName: 'FLOCI_AZ_BASE_URL',
    hostnameEnvName: 'FLOCI_AZ_HOSTNAME',
    storageModeEnvName: 'FLOCI_AZ_STORAGE_MODE',
    storagePathEnvName: 'FLOCI_AZ_STORAGE_PATH',
  },
  gcp: {
    cloud: 'gcp',
    image: 'floci/floci-gcp:latest',
    port: 4588,
    endpoint: 'http://localhost:4588',
    containerName: 'fdekit-floci-gcp',
    endpointEnvName: 'GCP_ENDPOINT_URL',
    portEnvName: 'FLOCI_GCP_PORT',
    baseUrlEnvName: 'FLOCI_GCP_BASE_URL',
    hostnameEnvName: 'FLOCI_GCP_HOSTNAME',
    storageModeEnvName: 'FLOCI_GCP_STORAGE_MODE',
    storagePathEnvName: 'FLOCI_GCP_STORAGE_PERSISTENT_PATH',
  },
} satisfies Record<FlociCloudProvider, FlociCloudDefaults>;
