export const dockerBackedServices = new Set([
  'lambda',
  'rds',
  'elasticache',
  'neptune',
  'msk',
  'ecs',
  'ec2',
  'eks',
  'opensearch',
  'codebuild',
  'functions',
  'azure-functions',
  'function-apps',
  'eventhubs',
  'event-hubs',
  'eventhub',
  'event-hub',
  'managed-kafka',
  'managedkafka',
  'kafka',
  'gcp-kafka',
  'cosmos-mongodb',
  'cosmos-mongo',
  'cosmosdb-mongodb',
  'cosmosdb-mongo',
  'cosmos-postgresql',
  'cosmos-postgres',
  'cosmosdb-postgresql',
  'cosmosdb-postgres',
  'cosmos-cassandra',
  'cosmosdb-cassandra',
  'cosmos-gremlin',
  'cosmosdb-gremlin',
  'azure-sql',
  'aks',
]);

export const awsServicePortMappings: Record<string, string[]> = {
  elasticache: ['6379-6399:6379-6399'],
  rds: ['7001-7099:7001-7099'],
  lambda: ['9200-9299:9200-9299'],
  opensearch: ['9200-9299:9200-9299'],
};

export const azureServicePortMappings: Record<string, string[]> = {
  eventhubs: ['5672:5672', '9093:9093'],
  'event-hubs': ['5672:5672', '9093:9093'],
  eventhub: ['5672:5672', '9093:9093'],
  'event-hub': ['5672:5672', '9093:9093'],
  cosmos: ['4578:4578'],
  cosmosdb: ['4578:4578'],
  'cosmos-nosql': ['4578:4578'],
  'cosmosdb-nosql': ['4578:4578'],
  'cosmos-mongodb': ['27017:27017'],
  'cosmos-mongo': ['27017:27017'],
  'cosmosdb-mongodb': ['27017:27017'],
  'cosmosdb-mongo': ['27017:27017'],
  'cosmos-postgresql': ['5432:5432'],
  'cosmos-postgres': ['5432:5432'],
  'cosmosdb-postgresql': ['5432:5432'],
  'cosmosdb-postgres': ['5432:5432'],
  'cosmos-cassandra': ['9042:9042'],
  'cosmosdb-cassandra': ['9042:9042'],
  'cosmos-gremlin': ['8182:8182'],
  'cosmosdb-gremlin': ['8182:8182'],
};

export const azureServiceEnvNames: Record<string, string[]> = {
  blob: ['FLOCI_AZ_SERVICES_BLOB_ENABLED'],
  blobs: ['FLOCI_AZ_SERVICES_BLOB_ENABLED'],
  queue: ['FLOCI_AZ_SERVICES_QUEUE_ENABLED'],
  queues: ['FLOCI_AZ_SERVICES_QUEUE_ENABLED'],
  table: ['FLOCI_AZ_SERVICES_TABLE_ENABLED'],
  tables: ['FLOCI_AZ_SERVICES_TABLE_ENABLED'],
  functions: ['FLOCI_AZ_SERVICES_FUNCTIONS_ENABLED'],
  'azure-functions': ['FLOCI_AZ_SERVICES_FUNCTIONS_ENABLED'],
  'function-apps': ['FLOCI_AZ_SERVICES_FUNCTIONS_ENABLED'],
  appconfig: ['FLOCI_AZ_SERVICES_APP_CONFIG_ENABLED'],
  'app-config': ['FLOCI_AZ_SERVICES_APP_CONFIG_ENABLED'],
  'app-configuration': ['FLOCI_AZ_SERVICES_APP_CONFIG_ENABLED'],
  cosmos: ['FLOCI_AZ_SERVICES_COSMOS_ENABLED'],
  cosmosdb: ['FLOCI_AZ_SERVICES_COSMOS_ENABLED'],
  'cosmos-nosql': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_NOSQL_ENABLED'],
  'cosmosdb-nosql': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_NOSQL_ENABLED'],
  'cosmos-table': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_TABLE_ENABLED'],
  'cosmosdb-table': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_TABLE_ENABLED'],
  'cosmos-mongodb': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_MONGODB_ENABLED'],
  'cosmos-mongo': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_MONGODB_ENABLED'],
  'cosmosdb-mongodb': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_MONGODB_ENABLED'],
  'cosmosdb-mongo': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_MONGODB_ENABLED'],
  'cosmos-postgresql': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_POSTGRESQL_ENABLED'],
  'cosmos-postgres': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_POSTGRESQL_ENABLED'],
  'cosmosdb-postgresql': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_POSTGRESQL_ENABLED'],
  'cosmosdb-postgres': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_POSTGRESQL_ENABLED'],
  'cosmos-cassandra': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_CASSANDRA_ENABLED'],
  'cosmosdb-cassandra': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_CASSANDRA_ENABLED'],
  'cosmos-gremlin': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_GREMLIN_ENABLED'],
  'cosmosdb-gremlin': ['FLOCI_AZ_SERVICES_COSMOS_ENABLED', 'FLOCI_AZ_SERVICES_COSMOS_ENGINES_GREMLIN_ENABLED'],
};

export const gcpServiceEnvNames: Record<string, string[]> = {
  gcs: ['FLOCI_GCP_SERVICES_GCS_ENABLED'],
  storage: ['FLOCI_GCP_SERVICES_GCS_ENABLED'],
  pubsub: ['FLOCI_GCP_SERVICES_PUBSUB_ENABLED'],
  'pub-sub': ['FLOCI_GCP_SERVICES_PUBSUB_ENABLED'],
  firestore: ['FLOCI_GCP_SERVICES_FIRESTORE_ENABLED'],
  datastore: ['FLOCI_GCP_SERVICES_DATASTORE_ENABLED'],
  iam: ['FLOCI_GCP_SERVICES_IAM_ENABLED'],
  'secret-manager': ['FLOCI_GCP_SERVICES_SECRETMANAGER_ENABLED'],
  secretmanager: ['FLOCI_GCP_SERVICES_SECRETMANAGER_ENABLED'],
  kafka: ['FLOCI_GCP_SERVICES_KAFKA_ENABLED'],
  'managed-kafka': ['FLOCI_GCP_SERVICES_KAFKA_ENABLED'],
  managedkafka: ['FLOCI_GCP_SERVICES_KAFKA_ENABLED'],
  'gcp-kafka': ['FLOCI_GCP_SERVICES_KAFKA_ENABLED'],
};
