import type { EvalCaseResult } from '@fdekit/runtime';
import type { ConsoleData, ConsoleMetrics } from '../interfaces/index.js';
import { csvCell } from '../view-models/format.js';

type CsvRow = Array<string | number>;

export function renderDashboardCsv(
  data: ConsoleData,
  metrics: ConsoleMetrics,
  createdAt: string,
  evalCases: EvalCaseResult[],
): string {
  const csvRows: CsvRow[] = [
    ['record_type', 'id', 'created_at', 'status', 'title', 'detail', 'destination', 'url', 'latency_ms', 'cost_usd', 'trace_id'],
    ...metrics.runHistory.map((run) => [
      'run',
      run.traceId,
      run.createdAt,
      run.status,
      run.finalAnswer ?? '',
      run.toolCalls.join(' | '),
      '',
      '',
      String(Math.round(run.latencyMs)),
      run.costUsd.toFixed(6),
      run.traceId,
    ]),
    ...metrics.createdIssues.map((issue) => [
      'issue',
      issue.id,
      issue.createdAt,
      issueModeStatus(issue.mode),
      issue.title,
      issue.tracker,
      issue.destination ?? '',
      issue.url ?? '',
      '',
      '',
      issue.traceId,
    ]),
    ...metrics.slackMessages.map((message) => [
      'slack',
      message.ts ?? message.traceId,
      message.createdAt,
      message.mode ?? '',
      message.channel,
      message.text,
      message.ticketId ?? '',
      '',
      '',
      '',
      message.traceId,
    ]),
    ...metrics.approvalQueue.map((approval) => [
      'approval',
      approval.approvalId ?? `${approval.traceId}:${approval.toolName}`,
      approval.createdAt,
      approval.status,
      approval.toolName,
      approval.reason,
      approval.policy,
      '',
      '',
      '',
      approval.traceId,
    ]),
    ...metrics.policyDefinitions.map((policy) => [
      'policy',
      `${policy.scope}:${policy.name}`,
      createdAt,
      policy.kind,
      policy.name,
      policy.detail,
      policy.scope,
      '',
      '',
      '',
      '',
    ]),
    ...metrics.businessImpact.map((item) => [
      'business_impact',
      item.label,
      createdAt,
      item.status,
      item.value,
      item.detail,
      '',
      '',
      '',
      '',
      '',
    ]),
    ...metrics.fieldMethod.scorecard.map((item) => [
      'workflow_scorecard',
      item.label,
      createdAt,
      item.status,
      item.value,
      item.detail,
      metrics.fieldMethod.workflowName,
      '',
      '',
      '',
      '',
    ]),
    ...metrics.fieldMethod.dataLayers.map((item) => [
      'data_layer',
      item.label,
      createdAt,
      item.status,
      item.value,
      item.detail,
      metrics.fieldMethod.workflowName,
      '',
      '',
      '',
      '',
    ]),
    ...metrics.fieldMethod.outcomeMetrics.map((item) => [
      'outcome_metric',
      item.label,
      createdAt,
      item.status,
      item.value,
      item.detail,
      metrics.fieldMethod.workflowName,
      '',
      '',
      '',
      '',
    ]),
    ...metrics.fieldMethod.rolloutStages.map((stage, index) => [
      'rollout_stage',
      String(index + 1),
      createdAt,
      stage === metrics.fieldMethod.rolloutStage ? 'current' : '',
      stage,
      stage === metrics.fieldMethod.rolloutStage ? metrics.fieldMethod.rolloutNext : '',
      metrics.fieldMethod.workflowName,
      '',
      '',
      '',
      '',
    ]),
    ...metrics.harness.phases.map((item) => [
      'harness_phase',
      item.label,
      createdAt,
      item.status,
      item.value,
      item.detail,
      metrics.harness.name,
      '',
      '',
      '',
      '',
    ]),
    ...metrics.harness.references.map((item) => [
      'harness_reference',
      item.label,
      createdAt,
      item.status,
      item.value,
      item.detail,
      metrics.harness.name,
      '',
      '',
      '',
      '',
    ]),
    ...metrics.integrationReadiness.map((item) => [
      'integration_readiness',
      item.label,
      createdAt,
      item.status,
      item.label,
      item.detail,
      '',
      '',
      '',
      '',
      '',
    ]),
    ...metrics.productionReadiness.map((item) => [
      'production_readiness',
      item.label,
      createdAt,
      item.status,
      item.label,
      item.detail,
      '',
      '',
      '',
      '',
      '',
    ]),
    ...metrics.enforcementPosture.map((item) => [
      'enforcement_posture',
      item.label,
      createdAt,
      item.status,
      item.label,
      item.detail,
      metrics.enforcementMode,
      '',
      '',
      '',
      '',
    ]),
    ...metrics.auditLog.slice(-12).map((entry) => [
      'audit',
      entry.id,
      entry.createdAt,
      entry.outcome,
      entry.action,
      entry.message ?? '',
      [entry.toolName, entry.policy, entry.approvalId].filter(Boolean).join(' | '),
      '',
      '',
      '',
      entry.traceId ?? entry.runId ?? '',
    ]),
    ...evalCases.map((evalCase) => [
      'eval_case',
      evalCase.traceId ?? evalCase.name,
      data.latestEval?.createdAt ?? createdAt,
      evalCase.status,
      evalCase.name,
      (evalCase.toolCalls ?? []).join(' | '),
      data.latestEval?.deployment ?? data.deployment.name,
      '',
      '',
      '',
      evalCase.traceId ?? '',
    ]),
  ];

  return csvRows.map((row) => row.map(csvCell).join(',')).join('\n') + '\n';
}

function issueModeStatus(mode: string | undefined): string {
  if (mode === 'local') {
    return 'simulated-local';
  }

  return mode ?? '';
}
